### ISSUE TITLE
Android build failed due to `build.gradle` line 59

### ISSUE THREAD

**Issue by trietbui85** [EdwynZN/GameshopDeal#1]
I get this error while building Android app
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/trietbui/FlutterProj/GameshopDeal/android/app/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

The Flutter Doctor is:
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-VN)
    • Flutter version 1.22.6 at /Users/trietbui/Library/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/trietbui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/trietbui/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
```

**Comment by EdwynZN** [comment]
Thank you for reaching out, that error is related to the key I use to build a release app with play store (which is not in the github code for security reasons), if you want to test out the app in debug mode go to `android/app/build.gradle` and comment `signingConfigs` and change in release to `signingConfigs.debug`

```
/// comment this
/*signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }*/

buildTypes {
        release {
            /// signingConfig signingConfigs.release use debug mode instead so `flutter run --release` works.
            signingConfig signingConfigs.debug
            /* You can comment this too, is not important for debugging
            shrinkResources true
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            */
        }
    }
```

**Comment by trietbui85** [comment]
Thanks. That fix works for me 👍

**Comment by ktktk22** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\96654\StudioProjects\mulim\android\app\build.gradle' line: ??

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 7.2. Current version is 5.4.1. If using the gradle wrapper, try editing the distributionUrl in C:\Users\96654\StudioProjects\mulim\android\gradle\wrapper\gradle-wrapper.properties to gradle-7.2-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ktktk22** [comment]
I have a problem

**Comment by EdwynZN** [comment]
@ktktk22 try to change in android/build.gradle

`classpath 'com.android.tools.build:gradle:7.3.0'`

and in android/gradle/wrapper/gradle-wrapper.properties

`distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip`
